# Config for train.py

project: pnca-clustered-split
run_name: codon-split-long
dataset_path: datasets/codon_graph_dict.pkl

seed: 42
use_wandb: true
sweep: false
save_path: "../saved_models/${project}/${run_name}"

cutoff_distance: 12
num_node_features: 18
batch_size: 256
hidden_channels: 256
dropout: 0.6
edge_weight_func: "exp"
edge_weight_lambda: 2
learning_rate: 4e-5
weight_decay: 5e-6
epochs: 2000
self_loops: false
lr_scheduling: false
normalise_ews: true
early_stop: false